package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

import controller.ButtonController;
import model.Utility;

@SuppressWarnings("serial")
public class AddCourierScreen extends JPanel
{
	private JButton saveButton, backButton, logoutButton;
	private JLabel imageFrame;
	private JPanel addCourierContainer, southButtonContainer, mainPane, imgContainer;

	protected final static String filePath = System.getProperty("user.dir"); 
    protected final static String separator = System.getProperty("file.separator");
    private BufferedImage acmeCourierServiceLogo;
    
    private JTextField courierIdField = new JTextField("<auto-generated>");
	private JTextField courierNameField = new JTextField("", 28);
    
    private ButtonController addCourierController;
    
    public AddCourierScreen(ButtonController buttonController)
    {
    	addCourierController = buttonController;
    	
    	mainPane = new JPanel();
    	mainPane.setLayout(new BoxLayout(mainPane, BoxLayout.Y_AXIS));
    	
		buttonController.setViewListener(new ViewListener(){
			public Object GetView() {
				return AddCourierScreen.this;
			}			
		});
		
    	// Container for the menu buttons
    	addCourierContainer = new JPanel();
    	Border border = new LineBorder(Color.BLUE, 1);
    	Border margin = new EmptyBorder(0, 50, 0, 50);
    	addCourierContainer.setBorder(new CompoundBorder(margin, border));
    	addCourierContainer.setAlignmentX(CENTER_ALIGNMENT);
    	addCourierContainer.setAlignmentY(CENTER_ALIGNMENT);
    	
    	southButtonContainer = new JPanel();
    	southButtonContainer.setBorder(new EmptyBorder(75, 5, 5, 5));
    	southButtonContainer.setLayout(new BoxLayout(southButtonContainer, BoxLayout.X_AXIS));
    	
		// Set the Logo image for the North part of the window
		try 
		{ 
			acmeCourierServiceLogo = ImageIO.read(new File(filePath + separator + "images" + separator + "smACMECourierServiceLogo.png"));
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}
		
    	/*
    	 *  Setup the images for each button
    	 */
    	// Save Button
    	Image saveButtonIcon = Utility.getImage(filePath + separator + "images" + separator + "saveButton.png");
    	saveButton = new JButton(new ImageIcon(saveButtonIcon));     	
    	
    	// Back Button
    	Image backButtonIcon = Utility.getImage(filePath + separator + "images" + separator + "backButton2.png");
    	backButton = new JButton(new ImageIcon(backButtonIcon));
    	
    	// Logout Button
		Image logoutButtonIcon = Utility.getImage(filePath + separator + "images" + separator + "logoutButton.png");
		logoutButton = new JButton(new ImageIcon(logoutButtonIcon));
    	
    	// Setup the View
    	SetUpView();      	
    }
    
    public void SetUpView()
    {
        /*
         *  Logo header
         */
        imgContainer = new JPanel();	
		imgContainer.setSize(new Dimension(75, 50));
		imageFrame = new JLabel();
		imageFrame = new JLabel(new ImageIcon(acmeCourierServiceLogo));
		imgContainer.add((Component)imageFrame);
		imgContainer.setBorder(new EmptyBorder(0, 10, 10, 10));
		mainPane.add(imgContainer, BorderLayout.NORTH);
		
		/*
		 *  Outer box for the Main Menu buttons
		 */
		addCourierContainer.setLayout(new BoxLayout(addCourierContainer, BoxLayout.Y_AXIS));
		addCourierContainer.setOpaque(false);

		JPanel addCourierScreenTitle = new JPanel();
		addCourierScreenTitle.setLayout(new BoxLayout(addCourierScreenTitle, BoxLayout.X_AXIS));
		addCourierScreenTitle.setBorder(new EmptyBorder(15, 15, 0, 175));
		
		
		// -- Add Courier Screen Label
		JLabel addCourierScreenLabel = new JLabel();
		addCourierScreenLabel.setText("Add a Courier:");
		addCourierScreenLabel.setFont(new Font("Calibri", Font.PLAIN, 28));
		addCourierScreenLabel.setBorder(new EmptyBorder(5, 5, 0, 500));
		addCourierScreenLabel.setAlignmentX(LEFT_ALIGNMENT);
		addCourierScreenTitle.add(addCourierScreenLabel);
		
		addCourierContainer.add(addCourierScreenTitle);
		
		/*
		 *  Inner first container for Courier ID field
		 */
		JPanel courierIdContainer = new JPanel();
		courierIdContainer.setLayout(new BoxLayout(courierIdContainer, BoxLayout.X_AXIS));
		courierIdContainer.setBorder(new EmptyBorder(75, 25, 10, 25));
		
			// -- Courier ID Label
			JLabel courierIdLabel = new JLabel();
			courierIdLabel.setText("Courier ID:");
			courierIdLabel.setFont(new Font("Calibri", Font.PLAIN, 24));
			courierIdLabel.setAlignmentX(LEFT_ALIGNMENT);
			//courierIdContainer.add(courierIdLabel);
			
			// -- Courier ID TextField
			Border borderO1 = new LineBorder(Color.BLUE, 1);
	    	Border marginO2 = new EmptyBorder(0, 60, 0, 25);
			courierIdField.setHorizontalAlignment(JTextField.LEFT);
			courierIdField.setOpaque(false);
			courierIdField.setFont(new Font("Calibri", Font.PLAIN, 28));
			courierIdField.setBorder(new CompoundBorder(marginO2, borderO1));
			courierIdField.setEditable(false);
			//courierIdContainer.add(courierIdField);
		
		// -- end of Courier ID Field
		addCourierContainer.add(courierIdContainer);
			
		/*
		 *  Inner second container for Courier Name field
		 */
		JPanel courierNameContainer = new JPanel();
		courierNameContainer.setLayout(new BoxLayout(courierNameContainer, BoxLayout.X_AXIS));
		courierNameContainer.setBorder(new EmptyBorder(15, 25, 5, 25));
		
			// -- Courier Name Label
			JLabel courierNameLabel = new JLabel();
			courierNameLabel.setText("Courier Name:");
			courierNameLabel.setFont(new Font("Calibri", Font.PLAIN, 24));
			courierNameLabel.setAlignmentX(LEFT_ALIGNMENT);
			courierNameContainer.add(courierNameLabel);
			
			// Used to "pretty" up the Text Field
			JPanel nameTextboxContainer = new JPanel();
			nameTextboxContainer.setLayout(new FlowLayout(FlowLayout.CENTER));
			nameTextboxContainer.setBorder(new EmptyBorder(0, 25, 0, 25));
			
			// -- Courier Name TextField
	    	courierNameField.setHorizontalAlignment(JTextField.LEFT);
	    	courierNameField.setFont(new Font("Calibri", Font.PLAIN, 28));
	    	courierNameField.setBorder(new LineBorder(Color.BLUE, 1));
	    	nameTextboxContainer.add(courierNameField);
			courierNameContainer.add(nameTextboxContainer);
		
		// -- end of 1st "New Password" Field
		addCourierContainer.add(courierNameContainer);
				
		JPanel saveButtonContainer = new JPanel();
		saveButtonContainer.setLayout(new BoxLayout(saveButtonContainer, BoxLayout.X_AXIS));
		saveButtonContainer.setBorder(new EmptyBorder(50, 0, 50, 0));
		
        // -- Save Button
		saveButton.setName("saveButton");
		saveButton.setOpaque(false);
		saveButton.setContentAreaFilled(false);
		saveButton.setBorder(new EmptyBorder(5, 0, 0, 0));
		saveButton.addActionListener(addCourierController);
		saveButtonContainer.add(saveButton, BorderLayout.CENTER);
		
		addCourierContainer.add(saveButtonContainer);

		// --- end of Box for Menu buttons
		
		mainPane.add(addCourierContainer, BorderLayout.CENTER);
		
		/*
		 * southButtonContainer for Back and Logout buttons
		 */
        // -- Back Button
		backButton.setName("courierMaintBackButton");
		backButton.setOpaque(false);
		backButton.setContentAreaFilled(false);
		backButton.setBorder(new EmptyBorder(10, 0, 0, 215));
		backButton.addActionListener(addCourierController);
		southButtonContainer.add(backButton);
		
		// -- Logout Button
		logoutButton.setName("logoutButton");
		logoutButton.setOpaque(false);
		logoutButton.setContentAreaFilled(false);
		logoutButton.setBorder(new EmptyBorder(10, 215, 0, 0));
		logoutButton.addActionListener(addCourierController);
		southButtonContainer.add(logoutButton);
		
		// -- end of southButtonContainer
		
		mainPane.add(southButtonContainer, BorderLayout.SOUTH);
		this.add(mainPane);
    }
    
    public void SetCourierID(String courierID)
    {
    	this.courierIdField.setText(courierID);
    }
    
    public String GetCourierName()
    {
    	return courierNameField.getText();
    }
}
